version: '3'

services:
  spark-master:
    image: hadoop-spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"  # Spark Master UI
      - "8080:8080"  # Spark Master Dashboard
    command: [ "sh", "-c", "service ssh start; /usr/local/spark/sbin/start-master.sh; tail -f /dev/null" ]

  spark-worker-1:
    image: hadoop-spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    command: [ "sh", "-c", "service ssh start; /usr/local/spark/sbin/start-worker.sh spark://spark-master:7077; tail -f /dev/null" ]

  spark-worker-2:
    image: hadoop-spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    command: [ "sh", "-c", "service ssh start; /usr/local/spark/sbin/start-worker.sh spark://spark-master:7077; tail -f /dev/null" ]
